# Basic
title: Francesca M. Cassola
subtitle: Behavioural Ecologist and Science Communicator
welcome_message: From behaviour to conservation, with a passion for storytelling.
description: MSCA Postdoctoral Research Fellow at Anglia Ruskin University, Cambridge, Uk
creator: Francesca M. Cassola

url: "https://francescamcassola.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# Blog path by language (usati solo per costruire i file)
blogs:
  it: /it/blog
  es: /es/blog

nav:
  - {title: Blog, description: Updates and reflections from my work, url: '/blog'}
  - {title: Projects, description: My Projects, url: '/projects'}
  - {title: CV, description: Education and publications, url: '/cv'}

# Pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ''
    # duoshuo: 
    
# Social
social:
  linkedin: https://www.linkedin.com/in/francescamauracassola/
  twitter: https://x.com/xisca_cassola
  bluesky: https://bsky.app/profile/xiscacassola.bsky.social
  orcid: https://orcid.org/0000-0002-0849-0070
  researchgate: https://www.researchgate.net/profile/Francesca-Cassola


# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
